# Day 1: Introduction Numpy and PyTorch

On the first day, we will cover:

> (in the morning)
>* Python Basics: data types (list, dictionary, set, tuple), function, class
>* Numpy: array, indexing, matrix operation, broadcasting, sort

>(in the afternoon)
>* PyTorch Basics: tensors, computational graph, automatic differentiation, custom modules and parameters


Adapted from the `CS231n` Python tutorial by Justin Johnson (http://cs231n.github.io/python-numpy-tutorial/).

## Python Basics
Python is a great general-purpose programming language on its own, but with the help of a huge number of open-source libraries including core libraries (such as numpy, scipy, pandas, matplotlib), libraries for machine learning (Scikit-learn), for deep learning (such as PyTorch, Keras, TensorFlow, and Theano) it becomes a powerful environment for data science.

We expect that some of you may already have some experience with Python and Numpy, or even PyTorch; for the rest of you, today's section will be a quick crash course on the python programming language and on the use of PyTorch for scientific computing.

### Numbers
Integers and floats 

In [1]:
#@title
x = 26
y = 26.0
print(x, type(x), y, type(y))

26 <class 'int'> 26.0 <class 'float'>


and we can do operations:

In [2]:
print(x + 1) # addition;
print(x - 1) # subtraction;
print(x * 5) # multiplication;
print(x / 4) # float devision;
print(x // 4) #integer division;
print(x ** 2) # exponentiation;

27
25
130
6.5
6
676


### Strings

In [3]:
# either '' or "" work to define strings
word1 = 'hello world!'
word2 = "hello world!"
print(word1, len(word1))
print(word2, len(word2))

hello world! 12
hello world! 12


Operations on strings can be:

In [4]:
print(word1.capitalize())  # Capitalize a string
print(word1.upper())       # Convert a string to uppercase
print(word1.replace('world', 'python'))  # Replace all instances of one substring with another;

Hello world!
HELLO WORLD!
hello python!


### Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [5]:
l1 = [1, 2, 3, 4, 5] # create a list with 5 elements
print(l1, l1[1]) # indexing of a list; count from 0 instead of 1, therefore l1[1] is 2 instead of 1.
print(l1[-1], l1[-2]) # negative indices count from the end of the list, therefore l1[-1] is 5, l1[-2] is 4.

[1, 2, 3, 4, 5] 2
5 4


In [6]:
l1 [3] = "python" # lists can contain elements of different types
print(l1)

[1, 2, 3, 'python', 5]


In [7]:
l1.append("world") # add a new element to the end of the list
print(l1)

[1, 2, 3, 'python', 5, 'world']


#### List comprehensions
When programming, we want to transform one type of data into another, by using a list comprehension:

In [8]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


List comprehensions can also contain conditions:

In [9]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


### Indexing
In addition to accessing list elements one at a time, python also provides concise syntax to access sublists

In [10]:
l2 = list(range(5)) # range is a build-in function to create a list of integers
print(l2)

[0, 1, 2, 3, 4]


In [11]:

print(l2[2:4]) #use colon, get a sublist from index 2 to 4 (2 is inclusive and 4 is exclusive)


[2, 3]


In [12]:
print(l2[2:]) # sublist from index 2 to the end of the list

[2, 3, 4]


In [13]:
print(l2[:3]) # sublist from the start till 3 (exclusive)

[0, 1, 2]


### Dictionaries

A dictionary stores (key, value) pairs

In [14]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary
print('cat' in d)     # Check if a dictionary has a given key
d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish'])

cute
True
wet


### Sets
A set is an unordered collection of elements

In [15]:
animals = {'dog', 'cat', 'fish'}
print('dog' in animals) # check if an element is in a set
print('bird' in animals)

True
False


In [16]:
animals.add('fish') # adding an element that is already in the set does nothing
print(animals)
animals.add('bird')
print(animals)

{'dog', 'cat', 'fish'}
{'dog', 'cat', 'fish', 'bird'}


### Tuples
A tuple is an ordered list of values. It is similar to a list, but it can be used as keys in dictionaries and as elements of sets, while lists cannot.

In [17]:
d = {(x, x + 1): x for x in range(6)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print(type(t))
print(d[t])
print(d)

<class 'tuple'>
5
{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5}


### Functions
Python functions are defined using the **def** keyword, for example (be careful with the indent):

In [18]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(x, 'is', sign(x))

-1 is negative
0 is zero
1 is positive


Another example is as follows:

In [19]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!!!' % name.upper())
    else:
        print('Hello, %s!' % name)

hello('world')
hello('world', loud=True)

Hello, world!
HELLO, WORLD!!!


### Classes
Python also provides defining classes

In [20]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!!!' % self.name.upper())
        else:
            print('Hello, %s!' % self.name)

g = Greeter('world')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method;
g.greet(loud=True)   # Call an instance method;

Hello, world!
HELLO, WORLD!!!


## Numpy

Numpy is a core library for scientific computing in python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

To use Numpy, we first need to import the numpy package:

In [21]:
import numpy as np

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialise numpy arrays from nested Python lists, and access elements using square brackets:


In [22]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2]) # note that indices start from 0
a[0] = 5                 # Change an element of the array
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [23]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [24]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [25]:
a = np.zeros((3,1,2)) # create a rank 3 array of all zeros
print(a, a.shape)
print(a[0, 0, 0])
print(a[0, :, :], a[0, :, :].shape)
print(a[:, 0, 0], a[:, 0, 0].shape)

[[[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]] (3, 1, 2)
0.0
[[0. 0.]] (1, 2)
[0. 0. 0.] (3,)


In [26]:
b = np.ones((4,3,2,2))   # Create a rank 4 array of all ones
print(b)

[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]


In [27]:
c = np.full((2,2), 26) # Create a constant array
print(c)

[[26 26]
 [26 26]]


In [28]:
d = np.eye(3) # create an identity matrix
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
e = np.random.random((2,2)) # create an array filled with random values
print(e)

[[0.19223933 0.98257734]
 [0.56614957 0.22189189]]


### Array indexing

In [30]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array. Mixing integer indexing with slices yields an array of lower rank, while using only slices yields an array of the same rank as the original array:

In [31]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [32]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [33]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [34]:
a = np.array([[1,2], [3, 4], [5, 6]])
b = np.array([[1,2], [4, 4], [5, 5]])
bool_idx = (a == b)  # Find the elements of a that equals to the corresponding elements of b;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is == b.

print(bool_idx)

[[ True  True]
 [False  True]
 [ True False]]


In [35]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a == b])

[1 2 4 5]
[1 2 4 5]


### Array math
Basic mathematic functions operate "element-wise" on arrays, and are available both as operator overloads and as functions in the numpy module:

In [36]:
x = np.array([[1,2],[3,4]], dtype=np.float64) # force a particular datatype
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [37]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [38]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [39]:
# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [40]:
# Elementwise square root; produces the array
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


The dot-function is utilised to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:
 

In [41]:
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors
print(v.dot(w))
print(np.dot(v, w))

219
219


In [42]:
# Matrix / vector product; both produce the rank 1 array 
print(x, v)
print(x.dot(v))
print(np.dot(x, v))

[[1. 2.]
 [3. 4.]] [ 9 10]
[29. 67.]
[29. 67.]


In [43]:
# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [44]:
print(x)
print(np.sum(x))  # Compute sum of all elements;
print(np.sum(x, axis=0))  # Compute sum of each column;
print(np.sum(x, axis=1))  # Compute sum of each row; 

[[1. 2.]
 [3. 4.]]
10.0
[4. 6.]
[3. 7.]


Another useful is mean:


In [45]:
print(x)
print(np.mean(x)) # compute the average of the flattened array
print(np.mean(x, axis=0)) # compute the mean along the first axis
print(np.mean(x, axis=1)) # compute the mean along the last axis

[[1. 2.]
 [3. 4.]]
2.5
[2. 3.]
[1.5 3.5]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [46]:
print(x)
print(x.T)

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]


### Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.
For example, suppose that we want to add a constant vector to each row of a matrix. Numpy broadcasting allows us to perform this computation without actually multiple copies of the smaller array.

In [47]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension


Here are some applications of broadcasting:

In [48]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)
# print(v * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [49]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
print(x, v)
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[1 2 3]
 [4 5 6]] [1 2 3]
[[2 4 6]
 [5 7 9]]


In [50]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print(x, w)
print((x.T + w).T)

[[1 2 3]
 [4 5 6]] [4 5]
[[ 5  6  7]
 [ 9 10 11]]


In [51]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [52]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


### Sorting

Numpy provides functions to sort an array on demanded axis, for example

In [53]:
a = np.array([[1, 4, 0], [3, 1, 5]])
print(np.sort(a)) # sort along the last axis, i.e., axis=1

[[0 1 4]
 [1 3 5]]


In [54]:
print(np.sort(a, axis = None)) # array is flattend before sorting

[0 1 1 3 4 5]


In [55]:
print(np.sort(a, axis = 0)) # sort along the first axis

[[1 1 0]
 [3 4 5]]


To figure out the index data, i.e., the sorted order, argsort can be applied, which gives the indices that would sort an array.
For a rank 1 array:

In [56]:
x = np.array([3, 1, 2])
print(np.argsort(x))

[1 2 0]


For a rank 2 array:

In [57]:
x = np.array([[0, 3], [2, 2]])
print(np.argsort(x, axis = 0)) # sorts along the first axis
print(np.argsort(x, axis = 1)) # sort along the last axis

[[0 1]
 [1 0]]
[[0 1]
 [0 1]]



This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

### Exercise 1:
For the following 10*10 array A, 



> [[0.69145505, 0.86931882, 0.88576413, 0.82707554, 0.94754421, 0.54767962,  0.51818679, 0.27907936, 0.95212406, 0.22750068],

> [0.345638,   0.16172159, 0.87807572, 0.38444467, 0.84255332, 0.69666159,  0.43339905, 0.91927538, 0.58666126, 0.83215206],

>[0.91359442, 0.06356911, 0.37205853, 0.18242315, 0.37961342, 0.93335263,  0.34068447, 0.48598708, 0.24260729, 0.70004846],

>[0.75245372, 0.64147803, 0.84013461, 0.6152693,  0.02235612, 0.4492574,  0.55206705, 0.69409179, 0.1666939,  0.67387225],

>[0.30664677, 0.87559232, 0.07164895, 0.85516997, 0.77945438, 0.51948711,  0.18721151, 0.7690967 , 0.53605078, 0.55431431],

>[0.1750064,  0.95009262, 0.57121048, 0.87359026, 0.05715099, 0.43202169,  0.3648696,  0.24367817, 0.06807447, 0.46999578],

>[0.41121198, 0.10125657, 0.0869751,  0.91816382, 0.01738795, 0.19420588,  0.00127754, 0.19281699, 0.56083174, 0.55424236],

>[0.34467108, 0.18352578, 0.69203741, 0.48087863, 0.39596428, 0.28107969,  0.09727506, 0.11236618, 0.82687268, 0.22700161],

>[0.92788092, 0.87184167, 0.72492497, 0.94086364, 0.86998108, 0.35178978,  0.45463869, 0.0242793,  0.75607483, 0.21317889],

>[0.15680697, 0.13109825, 0.93463861, 0.78143659, 0.30680001, 0.67935342,  0.3583568,  0.7522564,  0.19810852, 0.22378965]],



answer the following questions by programming in numpy on[ Google Colaboratory](https://colab.research.google.com/notebooks/welcome.ipynb). Avoid therefor the explicit use of for and while loops as well as list comprehensions, but rather use numpy methods and operations to solve the tasks, as the strengths of numpy, its efficiency and clarity, lie within them.


1.   What is the row index in A that has the largest last element? 
2.   What is the row index in A that has the second largest last element?
3.   What are the row indices in A that have a row sum greater than 5?
4.   What is the sum of all elements of the form A[i, i+1] in A?
5.   Multiply elementwise every row in matrix A by the vector w [0.49039597 0.73424538 0.08249155 0.0488797  0.62525918 0.29331343 0.76435348 0.68825002 0.53465669 0.3399619], and then sum the results for every row
6.   Do the above task in 5. using a numpy implementation of the matrix multiplication
7.   Set all elements of A that are larger than 0.5 to 0. What is the sum of the resulting matrix?
8.   Subtract 1 from all elements of A that are smaller than 0.5. What is the sum of the resulting matrix?
9.   What is the sum of all elements in A, that are smaller than their column's mean?
10.  Create a diagonal matrix B of size 10*10, with B[i,i] = i


In [58]:
import numpy as np

A=np.array([[0.69145505, 0.86931882, 0.88576413, 0.82707554, 0.94754421, 0.54767962,  0.51818679, 0.27907936, 0.95212406, 0.22750068],
 [0.345638,   0.16172159, 0.87807572, 0.38444467, 0.84255332, 0.69666159,  0.43339905, 0.91927538, 0.58666126, 0.83215206],
[0.91359442, 0.06356911, 0.37205853, 0.18242315, 0.37961342, 0.93335263,  0.34068447, 0.48598708, 0.24260729, 0.70004846],
[0.75245372, 0.64147803, 0.84013461, 0.6152693,  0.02235612, 0.4492574,  0.55206705, 0.69409179, 0.1666939,  0.67387225],
[0.30664677, 0.87559232, 0.07164895, 0.85516997, 0.77945438, 0.51948711,  0.18721151, 0.7690967 , 0.53605078, 0.55431431],
[0.1750064,  0.95009262, 0.57121048, 0.87359026, 0.05715099, 0.43202169,  0.3648696,  0.24367817, 0.06807447, 0.46999578],
[0.41121198, 0.10125657, 0.0869751,  0.91816382, 0.01738795, 0.19420588,  0.00127754, 0.19281699, 0.56083174, 0.55424236],
[0.34467108, 0.18352578, 0.69203741, 0.48087863, 0.39596428, 0.28107969,  0.09727506, 0.11236618, 0.82687268, 0.22700161],
[0.92788092, 0.87184167, 0.72492497, 0.94086364, 0.86998108, 0.35178978,  0.45463869, 0.0242793,  0.75607483, 0.21317889],
[0.15680697, 0.13109825, 0.93463861, 0.78143659, 0.30680001, 0.67935342,  0.3583568,  0.7522564,  0.19810852, 0.22378965]])

w = np.array([0.49039597, 0.73424538, 0.08249155, 0.0488797,  0.62525918, 0.29331343, 0.76435348, 0.68825002, 0.53465669, 0.3399619])

1. What is the row index in A that has the largest last element? (Tip: use numpy)

In [59]:
row_index_largest_last_element = np.argmax(A[:,-1])
print(row_index_largest_last_element)

1


2. What is the row index in A that has the second largest last element?

In [60]:
# inefficient but simple
sorted_indices = np.argsort(A[:,-1])
row_index_second_largest_last_element = sorted_indices[-2]
print(row_index_second_largest_last_element)

2


3. What are the row indices in A that have a row sum greater than 5?

In [61]:
row_indices_sum_greater_than_5 = np.where(np.sum(A, axis=1) > 5)[0]
print(row_indices_sum_greater_than_5)

[0 1 3 4 8]


4. What is the sum of all elements of the form A\[i, i+1] in A? (Tip: Which mathematical concept is described here)

In [62]:
assert np.isclose(np.diag(A,k=1)[0], A[0,1])
sum_diag_plus_one = np.sum(np.diag(A,k=1))
print(sum_diag_plus_one)

4.06939908


5. Multiply elementwise every row in matrix A by the vector w \[0.49039597 0.73424538 0.08249155 0.0488797 0.62525918 0.29331343 0.76435348 0.68825002 0.53465669 0.3399619], and then sum the results for every row.

In [69]:
# result1[i,j] = A[i, j] * w[j]
result1 = A[:,:] * w[np.newaxis,:]
print(result1)
# result2[i] = sum_j result1[i,j]
result2 = np.sum(result1, axis=1)
print(result2)

[[0.33908677 0.63829333 0.07306806 0.0404272  0.59246072 0.16064179
  0.39607788 0.19207638 0.5090595  0.07734156]
 [0.16949948 0.11874333 0.07243383 0.01879154 0.5268142  0.2043402
  0.33127007 0.6326913  0.31366237 0.2829    ]
 [0.44802302 0.04667533 0.03069168 0.00891679 0.23735678 0.27376486
  0.26040336 0.33448062 0.12971161 0.2379898 ]
 [0.36900027 0.47100228 0.06930401 0.03007418 0.01397837 0.13177323
  0.42197437 0.47770869 0.08912401 0.22909089]
 [0.15037834 0.64289962 0.00591043 0.04180045 0.48736101 0.15237255
  0.14309577 0.52933082 0.28660314 0.18844575]
 [0.08582243 0.69760112 0.04712004 0.04270083 0.03573418 0.12671776
  0.27888935 0.16771151 0.03639647 0.15978066]
 [0.2016567  0.07434717 0.00717471 0.04487957 0.01087198 0.05696319
  0.00097649 0.1327063  0.29985244 0.18842129]
 [0.16902531 0.13475296 0.05708724 0.0235052  0.2475803  0.08244445
  0.07435253 0.07733603 0.44209301 0.0771719 ]
 [0.45502906 0.64014572 0.05980018 0.04598913 0.54396366 0.10318467
  0.34750466 

6. Do the above task in 5. using matrix multiplication. (The result should be identical to above, but you should use a numpy implementation of the matrix multiplication)

In [64]:
# result[i] = sum_j A[i, j] w[j] = (A @ w)[i]
result = np.dot(A, w)
print(result)
assert np.allclose(result, result2)

[3.01853317 2.67114631 2.00801385 2.30303029 2.62819786 1.67847435
 1.01784983 1.38534892 2.68904048 1.65319672]


7. Set all elements of A that are larger than 0.5 to 0. What is the sum of the resulting matrix?

In [65]:
newA = A.copy()
newA[newA > 0.5] = 0
print(np.sum(newA))

12.46007933


8. Subtract 1 from all elements of A that are smaller than 0.5. What is the sum of the resulting matrix?

In [66]:
newA = A.copy()
newA[newA < 0.5] -= 1
print(np.sum(newA))

-1.15357179


9. What is the sum of all elements in A, that are smaller than their column's mean?

In [67]:
column_mean = np.mean(A, axis=0)
index_smaller = np.where(A[:,:] < column_mean[np.newaxis,:])
print(np.sum(A[index_smaller]))

10.738627640000002


10. Create a diagonal matrix B of size 10*10, with B\[i,i] = i

In [68]:
B = np.diag(np.arange(0, 10))
print(B)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]
